#Persistent volume for DB-Mysql 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: app-network
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root
