#Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: app-network
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
